language: c

sudo: false

compiler:
    - gcc
    - clang

addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        - ubuntu-precise

addons:
    apt:
        packages:
        - libsdl2-dev
        - libsdl2-ttf-dev

before_script:
    - mkdir build
    - cd build
    - cmake ..

script: make -j2
