language: c

sudo: required

compiler:
    - gcc
    - clang

addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test

before_script:
    - mkdir build
    - cd build
    - cmake ..

script: make -j2
