language: c

sudo: required

compiler:
    - gcc
    - clang

install:
    - sudo add-apt-repository ppa:team-xbmc/ppa -y
    - sudo apt-get update -q
    - sudo apt-get install libsdl2-dev libsdl2-ttf-dev

addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        - ubuntu-precise

before_script:
    - mkdir build
    - cd build
    - cmake ..

script: make -j2
