SET(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_C_COMPILER   /usr/bin/i686-w64-mingw32-gcc)
set(CMAKE_CXX_COMPILER /usr/bin/i686-w64-mingw32-g++)
set(CMAKE_RC_COMPILER /usr/bin/i686-w64-mingw32-windres)
set(CMAKE_SHARED_LINK_C_FLAGS "")
set(CMAKE_FIND_ROOT_PATH "")
